version: '3.8'

services:
  postgresql:
    image: postgres:latest
    platform: linux/amd64
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: laon-medi
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
